"""Compute the downstream checklist after a document change and verify closure.

The cascade chains (m2-role-rules.md Cascading Updates / Project-Level
Rollups, plus the per-skill routing notes) are encoded once, as data, in
`.agents/document_graph.yaml`. This script is the deterministic half of the
observer pattern the workspace runs on: it computes *which* documents are
downstream of what just changed and reports which edges are not yet
accounted for. It never decides *whether* a downstream document actually
needs an edit and never writes anything - that judgment stays with the
agent, which must resolve every reported item explicitly.

Two modes:

- **Legacy (no --run-id):** an edge counts as closed when its target is in
  the touched set. Quick manual sanity checks.
- **Strict (--run-id R):** every required edge must have a kind-valid
  outcome row in `_closure_outcomes` for run R (see closure_outcomes.py).
  `touched` then only determines which downstream edges become required -
  it never resolves an edge by itself. This is the machine-verifiable
  closure the intake workflow uses.

Scope: outcomes are recorded per project/person/variant, and the same edge
may resolve differently for two scopes in one run - so check **one scope at
a time** (`--project`/`--person`/`--variant` filter the outcome rows; rows
whose scope field is empty apply to any scope, rows scoped to a different
value never apply). Stored rows are revalidated against the *current*
graph on load: a row for a removed edge or a no-longer-valid outcome is
warned about and ignored, not silently honored. For duplicate rows with
the same (run, project, person, variant, source, target) identity, the
latest wins - that's how a `gated` edge later becomes `updated` without
deleting history.

Usage:

    # Offline sanity check - name what was touched yourself:
    python check_cascade_closure.py --touched individual_metrics,evidence_log

    # Read the last N _skill_invocations rows (Documents touched column):
    python check_cascade_closure.py --from-log 1

    # Strict per-run closure for one scope:
    python check_cascade_closure.py --touched ... --run-id 2026-07-19-aslan-1to1 \
        --project <Project> --person "<Person>"

Exit code 0 when every required edge is closed; 1 otherwise.

A name in `--touched`/the log that the graph doesn't know is reported as
UNKNOWN - usually it means a new document type exists and
document_graph.yaml needs a node for it (same commit as the skill that
introduced it).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

# Graph notes quote Cyrillic sheet headings; a cp1252 Windows console would
# otherwise crash mid-print.
if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

sys.path.insert(0, str(Path(__file__).resolve().parent))

GRAPH_PATH = Path(__file__).resolve().parent.parent / "document_graph.yaml"

# Kind -> what an unresolved downstream edge means for the agent.
KIND_ACTION = {
    "direct": "CHECK  (must be updated in the same pass; stale = defect)",
    "judgment": "CHECK  (decide: update, or record no_change with a reason)",
    "gated": "GATE   (route via m2_input round; downstream doc frozen until the round is answered)",
    "script": "RUN    (regenerated by script, never hand-edited)",
}


def load_graph() -> dict:
    with GRAPH_PATH.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def build_alias_map(graph: dict) -> dict[str, str]:
    amap = {k.lower(): v for k, v in (graph.get("aliases") or {}).items()}
    for name in graph.get("documents", {}):
        amap.setdefault(name.lower(), name)
    return amap


def normalize(name: str, alias_map: dict[str, str]) -> str | None:
    key = name.strip().lower().removesuffix(".gsheet").removesuffix(".csv")
    return alias_map.get(key)


def graph_edge_kind(graph: dict, source: str, target: str) -> str | None:
    for edge in (graph.get("documents", {}).get(source) or {}).get("downstream") or []:
        if edge.get("to") == target:
            return edge.get("kind")
    return None


def build_resolved(rows: list[dict], graph: dict) -> tuple[dict[tuple[str, str], str], list[str]]:
    """Reduce outcome rows (already scope-filtered) to {(source, target):
    outcome}, applying latest-wins precedence per full identity and
    revalidating each winner against the *current* graph. Returns
    (resolved, warnings). Pure - unit-tested."""
    from closure_outcomes import VALID_OUTCOMES

    winners: dict[tuple, dict] = {}
    for rec in rows:
        identity = (rec.get("Run ID", ""), rec.get("Project", ""), rec.get("Person", ""),
                    rec.get("Route variant", ""), rec["Source node"], rec["Target node"])
        winners[identity] = rec  # later rows overwrite: latest wins

    resolved: dict[tuple[str, str], str] = {}
    warns: list[str] = []
    from closure_outcomes import REASON_REQUIRED

    for rec in winners.values():
        source, target, outcome = rec["Source node"], rec["Target node"], rec["Outcome"]
        kind = graph_edge_kind(graph, source, target)
        if kind is None:
            warns.append(f"stored outcome for {source} -> {target} ignored: "
                         "edge no longer exists in document_graph.yaml")
            continue
        if outcome not in VALID_OUTCOMES.get(kind, set()):
            warns.append(f"stored outcome {outcome!r} for {source} -> {target} ignored: "
                         f"not valid for current edge kind {kind!r}")
            continue
        if outcome in REASON_REQUIRED and not rec.get("Reason", "").strip():
            warns.append(f"stored outcome {outcome!r} for {source} -> {target} ignored: "
                         "reason is required but empty (manual edit or historical row)")
            continue
        resolved[(source, target)] = outcome
    return resolved, warns


def read_touched_from_log(last_n: int, project: str | None) -> tuple[set[str], list[str]]:
    """Union of `Documents touched` over the last N _skill_invocations rows
    (optionally filtered to one project). Returns (raw names, row labels)."""
    from pipeline_common import get_services, get_skill_invocations_sheet
    from sync_m2_source_docs_to_sheets import read_sheet_values

    services = get_services()
    sheet = get_skill_invocations_sheet(services)
    rows = read_sheet_values(services, sheet["id"])
    body = rows[1:] if rows else []
    if project:
        body = [r for r in body if len(r) > 3 and r[3].strip().lower() == project.strip().lower()]
    picked = body[-last_n:]
    touched: set[str] = set()
    labels: list[str] = []
    for r in picked:
        docs = r[6] if len(r) > 6 else ""
        touched.update(d for d in (p.strip() for p in docs.split(",")) if d)
        labels.append(f"{r[0] if r else '?'} | {r[1] if len(r) > 1 else '?'} | {docs or '(no documents listed)'}")
    return touched, labels


def walk(
    graph: dict,
    node: str,
    touched: set[str],
    visited_req: set[str],
    visited_cond: set[str],
    depth: int,
    conditional: bool,
    strict: bool,
    resolved: dict[tuple[str, str], str],
    open_items: list[str],
    lines: list[str],
) -> None:
    docs = graph["documents"]
    for edge in docs.get(node, {}).get("downstream") or []:
        target, kind = edge["to"], edge["kind"]
        indent = "    " * depth
        cond = "(if updated) " if conditional else ""
        outcome = resolved.get((node, target))
        if outcome:
            status = f"resolved: {outcome}"
        elif target in touched and not strict:
            status = "touched"
        else:
            status = KIND_ACTION.get(kind, "CHECK")
            if target in touched and strict:
                status = "touched, outcome NOT recorded - " + status
            if not conditional:
                item = f"{node} -> {target} [{kind}]"
                if item not in open_items:
                    open_items.append(item)
        line = f"{indent}{cond}{node} -> {target:28s} {status}"
        if kind == "script":
            line += f"  [{edge.get('script', '?')}]"
        lines.append(line)
        note = edge.get("note")
        if note:
            lines.append(f"{indent}    - {' '.join(str(note).split())}")
        # The target's own downstream is required only if the target actually
        # changed - touched, or resolved as updated/regenerated. no_change and
        # gated leave it conditional.
        target_changed = target in touched or outcome in ("updated", "regenerated")
        child_conditional = conditional or not target_changed
        # Requiredness-aware traversal: a required visit dominates an earlier
        # conditional one (diamond case: A->X no_change, B->X updated must
        # still surface X's own required edges), so revisit when the state
        # upgrades. Conditional visits never add anything to an already
        # walked node.
        if not child_conditional:
            if target not in visited_req:
                visited_req.add(target)
                walk(graph, target, touched, visited_req, visited_cond, depth + 1,
                     False, strict, resolved, open_items, lines)
        else:
            if target not in visited_req and target not in visited_cond:
                visited_cond.add(target)
                walk(graph, target, touched, visited_req, visited_cond, depth + 1,
                     True, strict, resolved, open_items, lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--touched", default="", help="comma-separated document names that were updated")
    parser.add_argument("--from-log", type=int, default=0, metavar="N",
                        help="also read the last N _skill_invocations rows' Documents touched")
    parser.add_argument("--run-id", default=None,
                        help="strict mode: every required edge needs a kind-valid "
                             "_closure_outcomes row for this run (closure_outcomes.py)")
    parser.add_argument("--project", default=None,
                        help="scope filter for --from-log rows and --run-id outcomes")
    parser.add_argument("--person", default=None, help="scope filter for --run-id outcomes")
    parser.add_argument("--variant", default=None,
                        help="source route variant filter for --run-id outcomes")
    args = parser.parse_args()

    if not args.touched and not args.from_log:
        parser.error("nothing to check: pass --touched and/or --from-log N")

    graph = load_graph()
    alias_map = build_alias_map(graph)
    periodic = set(graph.get("periodic") or [])

    raw: set[str] = {t for t in (p.strip() for p in args.touched.split(",")) if t}
    if args.from_log:
        log_touched, labels = read_touched_from_log(args.from_log, args.project)
        raw |= log_touched
        print("_skill_invocations rows considered:")
        for label in labels:
            print(f"  {label}")
        print()

    touched: set[str] = set()
    unknown: list[str] = []
    for name in sorted(raw):
        canon = normalize(name, alias_map)
        if canon is None:
            unknown.append(name)
        elif canon not in periodic:
            touched.add(canon)

    if unknown:
        print("UNKNOWN document names (add a node or alias to document_graph.yaml):")
        for name in unknown:
            print(f"  {name}")
        print()

    if not touched:
        print("No known documents in the touched set - nothing to expand.")
        return 1 if unknown else 0

    strict = bool(args.run_id)
    resolved: dict[tuple[str, str], str] = {}
    if strict:
        from closure_outcomes import fetch_outcomes
        from pipeline_common import get_services
        rows = fetch_outcomes(get_services(), args.run_id,
                              project=args.project or "", person=args.person or "",
                              variant=args.variant or "")
        resolved, load_warns = build_resolved(rows, graph)
        scope = ", ".join(f"{k}={v}" for k, v in
                          (("project", args.project), ("person", args.person),
                           ("variant", args.variant)) if v)
        print(f"Run {args.run_id}: {len(resolved)} usable outcome(s)"
              + (f" [{scope}]" if scope else "") + " - strict mode, every required "
              "edge needs a recorded outcome\n")
        for w in load_warns:
            print(f"  WARN {w}")
        if load_warns:
            print()

    print(f"Touched: {', '.join(sorted(touched))}\n")
    open_items: list[str] = []
    lines: list[str] = []
    visited_req = set(touched)
    visited_cond: set[str] = set()
    for node in sorted(touched):
        walk(graph, node, touched, visited_req, visited_cond, 0, False, strict,
             resolved, open_items, lines)

    if lines:
        print("Cascade checklist (nested lines fire only if their parent gets updated):")
        for line in lines:
            print(f"  {line}")
    else:
        print("Touched documents have no downstream edges.")

    print()
    if open_items or unknown:
        print(f"OPEN: {len(open_items)} required edge(s) unresolved"
              + (f", {len(unknown)} unknown name(s)" if unknown else "") + ".")
        if strict:
            print("Record each with closure_outcomes.py record (updated / no_change+reason /")
            print("gated+reason / regenerated), then re-run with the same --run-id and scope.")
        else:
            print("Resolve each explicitly: update it, run the named script, or state")
            print("'no change needed' with a reason in your reply (and evidence_log notes).")
        return 1
    print("CLOSED: every required edge in the cascade is accounted for.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
