"""Compute the downstream checklist after a document change and verify closure.

The cascade chains (m2-role-rules.md Cascading Updates / Project-Level
Rollups, plus the per-skill routing notes) are encoded once, as data, in
`.agents/document_graph.yaml`. This script is the deterministic half of the
observer pattern the workspace runs on: it computes *which* documents are
downstream of what just changed and reports which of them were not touched.
It never decides *whether* a downstream document actually needs an edit and
never writes anything - that judgment stays with the agent, which must
resolve every reported item explicitly ("updated" or "no change needed,
because ..."), not by silence.

Misalignment between documents has historically come from exactly one
failure shape: an agent updated the bottom of a chain and never visited a
node further up. This makes that omission visible instead of silent.

Usage:

    # Offline - name what was touched yourself:
    python check_cascade_closure.py --touched individual_metrics,evidence_log

    # Read the last N rows of _skill_invocations (Documents touched column)
    # and check closure for the union of what they report:
    python check_cascade_closure.py --from-log 1
    python check_cascade_closure.py --from-log 3 --project <Project>

Exit code 0 when every downstream node was touched; 1 when open items
remain (so the agent's final message must account for each one).

A name in `--touched`/the log that the graph doesn't know is reported as
UNKNOWN - usually it means a new document type exists and
document_graph.yaml needs a node for it (same commit as the skill that
introduced it).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

# Graph notes quote Cyrillic sheet headings; a cp1252 Windows console would
# otherwise crash mid-print.
if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

GRAPH_PATH = Path(__file__).resolve().parent.parent / "document_graph.yaml"

# Kind -> what an unresolved downstream node means for the agent.
KIND_ACTION = {
    "direct": "CHECK  (must be updated in the same pass; stale = defect)",
    "judgment": "CHECK  (decide: update, or state 'no change needed' explicitly)",
    "gated": "GATE   (route via m2_input round; downstream doc frozen until the round is answered)",
    "script": "RUN    (regenerated by script, never hand-edited)",
}


def load_graph() -> dict:
    with GRAPH_PATH.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def build_alias_map(graph: dict) -> dict[str, str]:
    amap = {k.lower(): v for k, v in (graph.get("aliases") or {}).items()}
    for name in graph.get("documents", {}):
        amap.setdefault(name.lower(), name)
    return amap


def normalize(name: str, alias_map: dict[str, str]) -> str | None:
    key = name.strip().lower().removesuffix(".gsheet").removesuffix(".csv")
    return alias_map.get(key)


def read_touched_from_log(last_n: int, project: str | None) -> tuple[set[str], list[str]]:
    """Union of `Documents touched` over the last N _skill_invocations rows
    (optionally filtered to one project). Returns (raw names, row labels)."""
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from pipeline_common import get_services, get_skill_invocations_sheet
    from sync_m2_source_docs_to_sheets import read_sheet_values

    services = get_services()
    sheet = get_skill_invocations_sheet(services)
    rows = read_sheet_values(services, sheet["id"])
    body = rows[1:] if rows else []
    if project:
        body = [r for r in body if len(r) > 3 and r[3].strip().lower() == project.strip().lower()]
    picked = body[-last_n:]
    touched: set[str] = set()
    labels: list[str] = []
    for r in picked:
        docs = r[6] if len(r) > 6 else ""
        touched.update(d for d in (p.strip() for p in docs.split(",")) if d)
        labels.append(f"{r[0] if r else '?'} | {r[1] if len(r) > 1 else '?'} | {docs or '(no documents listed)'}")
    return touched, labels


def walk(
    graph: dict,
    node: str,
    touched: set[str],
    visited: set[str],
    depth: int,
    conditional: bool,
    open_items: list[str],
    lines: list[str],
) -> None:
    docs = graph["documents"]
    for edge in docs.get(node, {}).get("downstream") or []:
        target, kind = edge["to"], edge["kind"]
        indent = "    " * depth
        cond = "(if updated) " if conditional else ""
        if target in touched:
            status = "touched"
        else:
            status = KIND_ACTION.get(kind, "CHECK")
            # A conditional branch is informational; a first-level miss is an open item.
            if not conditional:
                open_items.append(f"{node} -> {target} [{kind}]")
        line = f"{indent}{cond}{node} -> {target:28s} {status}"
        if kind == "script":
            line += f"  [{edge.get('script', '?')}]"
        lines.append(line)
        note = edge.get("note")
        if note:
            lines.append(f"{indent}    - {' '.join(str(note).split())}")
        if target not in visited:
            visited.add(target)
            walk(graph, target, touched, visited, depth + 1,
                 conditional or target not in touched, open_items, lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--touched", default="", help="comma-separated document names that were updated")
    parser.add_argument("--from-log", type=int, default=0, metavar="N",
                        help="also read the last N _skill_invocations rows' Documents touched")
    parser.add_argument("--project", default=None, help="with --from-log: only rows for this project")
    args = parser.parse_args()

    if not args.touched and not args.from_log:
        parser.error("nothing to check: pass --touched and/or --from-log N")

    graph = load_graph()
    alias_map = build_alias_map(graph)
    periodic = set(graph.get("periodic") or [])

    raw: set[str] = {t for t in (p.strip() for p in args.touched.split(",")) if t}
    if args.from_log:
        log_touched, labels = read_touched_from_log(args.from_log, args.project)
        raw |= log_touched
        print("_skill_invocations rows considered:")
        for label in labels:
            print(f"  {label}")
        print()

    touched: set[str] = set()
    unknown: list[str] = []
    for name in sorted(raw):
        canon = normalize(name, alias_map)
        if canon is None:
            unknown.append(name)
        elif canon not in periodic:
            touched.add(canon)

    if unknown:
        print("UNKNOWN document names (add a node or alias to document_graph.yaml):")
        for name in unknown:
            print(f"  {name}")
        print()

    if not touched:
        print("No known documents in the touched set - nothing to expand.")
        return 1 if unknown else 0

    print(f"Touched: {', '.join(sorted(touched))}\n")
    open_items: list[str] = []
    lines: list[str] = []
    visited = set(touched)
    for node in sorted(touched):
        walk(graph, node, touched, visited, 0, False, open_items, lines)

    if lines:
        print("Cascade checklist (nested lines fire only if their parent gets updated):")
        for line in lines:
            print(f"  {line}")
    else:
        print("Touched documents have no downstream edges.")

    print()
    if open_items or unknown:
        print(f"OPEN: {len(open_items)} downstream node(s) not reported as touched"
              + (f", {len(unknown)} unknown name(s)" if unknown else "") + ".")
        print("Resolve each explicitly: update it, run the named script, or state")
        print("'no change needed' with a reason in your reply (and evidence_log notes).")
        return 1
    print("CLOSED: every downstream node in the cascade was touched.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
