"""Slice the material for a qa-retro pass: everything since the last retro.

Reads `_skill_invocations`, finds the most recent row with
`Source type == retro` (the marker the previous retro wrote via
`log_skill_invocation`), and prints:

1. every invocation row after that marker (all rows if no retro has ever
   run), with `feedback:` notes flagged - those are the user
   corrections/overrides captured during intake passes, the primary retro
   input;
2. a cascade-closure check across that same window (see
   `find_direct_script_misses` below) - previously a manual, easy-to-skip
   step every retro pass had to remember to do itself;
3. repo commits over the same window (`git log` since the marker row's
   date), because rule changes already made by hand are part of the same
   picture.

Read-only: it gathers, it doesn't judge. Grouping, the repeat threshold,
and drafting edits are qa-retro's (the agent's) job. The retro itself,
once done, logs its own `retro` row - that's what makes the next run's
window start here.

Usage:
    python prepare_retro.py
"""

from __future__ import annotations

import io
import subprocess
import sys
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    if isinstance(sys.stdout, io.TextIOWrapper):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

sys.path.insert(0, str(Path(__file__).resolve().parent))

from check_cascade_closure import build_alias_map, load_graph, normalize
from pipeline_common import get_services, get_skill_invocations_sheet
from sync_m2_source_docs_to_sheets import read_sheet_values


def find_direct_script_misses(window_rows: list, graph: dict) -> list[tuple[str, str, str, str]]:
    """Group window rows by project, union each project's `Documents
    touched` tokens across the whole window (not just one row - a later
    pass on the same project can close what an earlier one left open), and
    flag any `direct`/`script`-kind downstream edge whose source was
    touched somewhere in that project's window but whose target never was.

    Only `direct` ("must be updated in the same pass; stale = defect") and
    `script` ("regenerated by script, never hand-edited") edges are
    checked - together under 25% of the graph's edges. `judgment`/`gated`
    edges are deliberately excluded: they're supposed to often stay open
    (a real "no update needed" call, or a round still pending an answer),
    so auto-flagging them would bury the few real signals in constant
    noise. This is a first-order check (touched -> its own direct/script
    targets), not a transitive walk - sufficient for the current graph,
    where no direct/script edge chain runs deeper than two hops and each
    hop is checked against the same real per-project touched set anyway.

    Pure - no I/O beyond the already-loaded graph. Returns a list of
    (project, source, target, kind) tuples, one per open edge."""
    periodic = set(graph.get("periodic") or [])
    docs = graph.get("documents", {})
    alias_map = build_alias_map(graph)

    by_project: dict[str, set[str]] = {}
    for row in window_rows:
        padded = list(row) + [""] * (8 - len(row))
        project, doc_field = padded[3], padded[6]
        if not project:
            continue
        touched = by_project.setdefault(project, set())
        for token in doc_field.split(","):
            canon = normalize(token, alias_map)
            if canon and canon not in periodic:
                touched.add(canon)

    misses: list[tuple[str, str, str, str]] = []
    for project, touched in sorted(by_project.items()):
        for source in sorted(touched):
            for edge in docs.get(source, {}).get("downstream") or []:
                kind, target = edge.get("kind"), edge.get("to")
                if kind in ("direct", "script") and target not in touched and target not in periodic:
                    misses.append((project, source, target, kind))
    return misses


def main() -> int:
    services = get_services()
    sheet = get_skill_invocations_sheet(services)
    rows = read_sheet_values(services, sheet["id"])
    body = rows[1:] if rows else []

    last_retro_idx = None
    for i, row in enumerate(body):
        if len(row) > 2 and row[2].strip().lower() == "retro":
            last_retro_idx = i

    if last_retro_idx is None:
        window = body
        since_date = None
        print("No previous retro row found - the window is the entire log.\n")
    else:
        window = body[last_retro_idx + 1:]
        marker = body[last_retro_idx]
        since_date = marker[0] if marker else None
        print(f"Last retro: {since_date} | notes: {marker[7] if len(marker) > 7 else ''}\n")

    if not window:
        print("No invocation rows since the last retro.")
    else:
        print(f"{len(window)} invocation row(s) since the last retro:\n")
        feedback_count = 0
        for row in window:
            padded = list(row) + [""] * (8 - len(row))
            date, source, stype, project, person, skills, docs, notes = padded[:8]
            flag = ""
            if "feedback:" in notes.lower():
                flag = "  <-- FEEDBACK"
                feedback_count += 1
            print(f"  {date} | {stype:18s} | {skills}")
            print(f"      source: {source}" + (f" | project: {project}" if project else "")
                  + (f" | person: {person}" if person else ""))
            if docs:
                print(f"      touched: {docs}")
            if notes:
                print(f"      notes: {notes}{flag}")
            print()
        print(f"feedback: notes in window: {feedback_count}")

        graph = load_graph()
        misses = find_direct_script_misses(window, graph)
        print()
        if misses:
            print(f"Cascade-closure check (direct/script edges, per project across "
                  f"the window): {len(misses)} candidate miss(es):")
            for project, source, target, kind in misses:
                print(f"  [{project}] {source} -> {target}  [{kind}] - target not in "
                      f"this project's touched set anywhere this window")
            print("  judgment/gated edges (most of the graph) are not checked here - "
                  "those need per-case review, not automatic flagging. Confirm each "
                  "candidate above is a real omission before treating it as a finding.")
        else:
            print("Cascade-closure check (direct/script edges): none open across "
                  "this window's per-project touched sets.")

    print()
    git_range = ["--since", since_date] if since_date else ["-20"]
    try:
        log = subprocess.run(
            ["git", "log", "--oneline", "--date=short", *git_range],
            capture_output=True, text=True, cwd=Path(__file__).resolve().parents[2],
            check=True,
        ).stdout.strip()
        header = (f"Repo commits since {since_date}:" if since_date
                  else "Recent repo commits (no retro marker, showing last 20):")
        print(header)
        print(log or "  (none)")
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        print(f"Could not read git log: {exc}")

    print()
    print("Next (qa-retro): group by target skill/reference/graph node; "
          "repeat threshold applies - once = trace, twice+ = draft an edit; "
          "finish by logging a source_type=retro row.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
