r"""Thin wrapper: record qa-management telemetry into the shared
ai-telemetry database (C:\Users\User\Documents\ai-telemetry by default).

This script does NOT talk to the database itself and does NOT reimplement
any of ai-telemetry's write/dedup logic - it just resolves which
ai-telemetry `record_*.py` script a given fact table needs, fills in this
project's own defaults (`--project-id=qa-management`,
`--source-system=native`) unless the caller already supplied them, and
execs that script with the rest of the arguments passed straight through.
All real validation (redaction, FK checks, the idempotent
project_id/source_system/source_ref dedup) happens inside ai-telemetry
itself, exactly as it does for any other caller of those scripts.

Generated by ai-telemetry's scripts/generate_project_wrapper.py from
templates/record_telemetry.py.template - the same wrapper pattern
deployed identically across every contributing project (see
ai-telemetry's own README "Recording native telemetry" and "Onboarding a
new project"). This copy is project-local (not shared/imported) so each
project's wrapper stays a plain, dependency-free script; if this
project has its own similarly-named telemetry tooling for a different
purpose (e.g. a load-test metrics exporter), that's a separate, unrelated
concern this wrapper does not touch or replace.

Usage
-----
    python .agents/scripts/record_telemetry.py <kind> [--ai-telemetry-path PATH] <rest of the record_<kind>.py args>

`<kind>` is one of: current-session, session, task, skill-invocation,
validation, command-run, artifact-touch, feedback-event - see
ai-telemetry's own README ("Recording native telemetry" and "Near-
automatic current-session recording") for each one's full flag list.

Examples
--------
    # Near-automatic - the recommended closeout command for a no-queue/
    # conversational pass (see this project's own AGENTS.md). Zero extra
    # flags needed in the common case: project_id comes from this
    # wrapper's own baked-in default (below), runtime/session auto-detect
    # from the current Claude Code/Codex environment.
    python .agents/scripts/record_telemetry.py current-session

    # See what WOULD be written - no DB write.
    python .agents/scripts/record_telemetry.py current-session --dry-run

    python .agents/scripts/record_telemetry.py session ^
        --runtime-id claude --session-id abc123 --date 2026-08-12

    python .agents/scripts/record_telemetry.py task ^
        --task-type project_task --date 2026-08-12 --status-normalized ok

    python .agents/scripts/record_telemetry.py validation ^
        --check-name pytest --status-normalized pass --date 2026-08-12

`current-session` is different from every other kind
-------------------------------------------------------
Every other kind forwards to a `record_*.py` script that always requires
explicit `--session-id`/`--runtime-id`/token flags. `current-session`
forwards to `record_current_agent_session.py`, which auto-detects as much
of that as it reliably can (Claude via `$CLAUDE_CODE_SESSION_ID`, Codex
via a recent-rollout-file cwd scan) and writes a CUMULATIVE SNAPSHOT row -
running it again later in the same long conversation is expected to add
further snapshot rows as the session grows (see ai-telemetry's own
README, "Near-automatic current-session recording", and
`scripts/report.py`'s `session_rows` vs `distinct_sessions` split for how
that's reported). It also does not accept `--source-system` at all
(always `native` internally) - this wrapper does not inject that flag for
`current-session`, unlike every other kind (see "Defaults" below).

`--source-ref` (idempotency key)
---------------------------------
Not supplied by this wrapper - pass `--source-ref <your-stable-id>`
yourself when you already have one (a CI run id, a task id - anything
you'd recognize on retry). If you omit it, the underlying ai-telemetry
script mints one itself and prints it prominently on stdout (this
wrapper never captures or hides that output) - reuse that exact printed
value via `--source-ref` on any retry instead of leaving it out again,
or a retry will insert a second row instead of being recognized as a
duplicate. (`current-session` mints a fresh one on every call by design -
see "current-session is different from every other kind" above; do not
try to force idempotency there via `--source-ref`, use
`--allow-duplicate-snapshot`'s absence instead, which is the real guard.)

Defaults (override by passing the flag explicitly)
----------------------------------------------------
    --project-id      qa-management            (every kind, including current-session)
    --source-system   native                     (every kind EXCEPT current-session - it has no such flag, always native internally)
    --ai-telemetry-path   C:\Users\User\Documents\ai-telemetry
                          (or $AI_TELEMETRY_PATH if set)
"""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

DEFAULT_PROJECT_ID = "qa-management"
DEFAULT_SOURCE_SYSTEM = "native"
DEFAULT_AI_TELEMETRY_PATH = r"C:\Users\User\Documents\ai-telemetry"

# kind -> ai-telemetry script that actually performs the write.
SCRIPT_MAP = {
    "current-session": "record_current_agent_session.py",
    "session": "record_session.py",
    "task": "record_task.py",
    "skill-invocation": "record_skill_invocation.py",
    "artifact-touch": "record_artifact_touch.py",
    "validation": "record_validation.py",
    "feedback-event": "record_feedback_event.py",
    "command-run": "record_command_run.py",
}

# Kinds whose target script has no --source-system flag at all (it's
# hardcoded internally instead) - injecting the flag anyway would make
# that script's own argparse fail with "unrecognized arguments". Keep
# this set in sync with SCRIPT_MAP: a kind belongs here only if its
# target script genuinely lacks the flag, never as a way to skip the
# default for a script that does accept it.
NO_SOURCE_SYSTEM_KINDS = {"current-session"}


def _has_flag(args: list[str], flag: str) -> bool:
    return any(a == flag or a.startswith(flag + "=") for a in args)


def main() -> int:
    argv = sys.argv[1:]
    if not argv or argv[0] in ("-h", "--help"):
        print(__doc__)
        print("kinds: " + ", ".join(sorted(SCRIPT_MAP)))
        return 0 if argv else 2

    kind = argv[0]
    rest = argv[1:]
    if kind not in SCRIPT_MAP:
        print(f"ERROR: unknown kind {kind!r}. Choose one of: {', '.join(sorted(SCRIPT_MAP))}", file=sys.stderr)
        return 2

    # --ai-telemetry-path is this wrapper's own flag, not forwarded -
    # pull it out of the passthrough args if present.
    ai_telemetry_path = os.environ.get("AI_TELEMETRY_PATH", DEFAULT_AI_TELEMETRY_PATH)
    passthrough: list[str] = []
    i = 0
    while i < len(rest):
        arg = rest[i]
        if arg == "--ai-telemetry-path":
            if i + 1 >= len(rest):
                print("ERROR: --ai-telemetry-path requires a value.", file=sys.stderr)
                return 2
            ai_telemetry_path = rest[i + 1]
            i += 2
            continue
        if arg.startswith("--ai-telemetry-path="):
            ai_telemetry_path = arg.split("=", 1)[1]
            i += 1
            continue
        passthrough.append(arg)
        i += 1

    target_script = Path(ai_telemetry_path) / "scripts" / SCRIPT_MAP[kind]
    if not target_script.exists():
        print(f"ERROR: {target_script} not found - check --ai-telemetry-path / $AI_TELEMETRY_PATH.", file=sys.stderr)
        return 1

    # Inject this project's own defaults unless the caller already
    # supplied them explicitly - never override an explicit caller value.
    if not _has_flag(passthrough, "--project-id"):
        passthrough = ["--project-id", DEFAULT_PROJECT_ID] + passthrough
    if kind not in NO_SOURCE_SYSTEM_KINDS and not _has_flag(passthrough, "--source-system"):
        passthrough = ["--source-system", DEFAULT_SOURCE_SYSTEM] + passthrough

    cmd = [sys.executable, str(target_script), *passthrough]
    result = subprocess.run(cmd)
    return result.returncode


if __name__ == "__main__":
    sys.exit(main())
